add_subdirectory(HelloWorld)
add_subdirectory(BasicDemo)
IF(BUILD_BULLET3)
	add_subdirectory(ExampleBrowser)
	add_subdirectory(RobotSimulator)
	add_subdirectory(SharedMemory)
	add_subdirectory(ThirdPartyLibs/Gwen)
	add_subdirectory(ThirdPartyLibs/BussIK)
	add_subdirectory(ThirdPartyLibs/clsocket)
	add_subdirectory(OpenGLWindow)
	add_subdirectory(TwoJoint)
ENDIF()

IF(BUILD_PYBULLET)
	add_subdirectory(pybullet)
ENDIF(BUILD_PYBULLET)
